// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-west-1",
    "aws_cognito_identity_pool_id": "eu-west-1:e6b83a57-e668-44c0-8a32-4c5176592c47",
    "aws_cognito_region": "eu-west-1",
    "aws_user_pools_id": "eu-west-1_7Ab9TygEV",
    "aws_user_pools_web_client_id": "2r2n7nct8ab9si42lmr6kce5tt",
    "oauth": {
        "domain": "comedylover-dev.auth.eu-west-1.amazoncognito.com",
        "scope": [
            "email",
            "openid",
            "profile",
            "aws.cognito.signin.user.admin"
        ],
        "redirectSignIn": "dailyjoke://main",
        "redirectSignOut": "dailyjoke://main",
        "responseType": "code"
    },
    "federationTarget": "COGNITO_USER_AND_IDENTITY_POOLS",
    "aws_appsync_graphqlEndpoint": "https://yseogg42n5bvbloyjufi75yje4.appsync-api.eu-west-1.amazonaws.com/graphql",
    "aws_appsync_region": "eu-west-1",
    "aws_appsync_authenticationType": "AWS_IAM",
    "aws_user_files_s3_bucket": "comedyloverimagebucket-dev",
    "aws_user_files_s3_bucket_region": "eu-west-1"
};


export default awsmobile;
